export const ALLOWED_UPLOAD_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/gif',
  'image/webp',
  'application/pdf',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'text/plain',
  'text/markdown',
  'application/json',
  'text/csv',
] as const

export const ALLOWED_UPLOAD_EXTENSIONS = [
  'pdf',
  'docx',
  'xls',
  'xlsx',
  'txt',
  'md',
  'json',
  'csv',
  'ts',
  'js',
  'py',
  'go',
  'java',
  'c',
  'cpp',
  'h',
  'hpp',
  'rs',
  'yaml',
  'yml',
  'toml',
] as const

export const PARSABLE_TEXT_EXTENSIONS = [
  'txt',
  'md',
  'json',
  'csv',
  'ts',
  'js',
  'py',
  'go',
  'java',
  'c',
  'cpp',
  'h',
  'hpp',
  'rs',
  'yaml',
  'yml',
  'toml',
] as const

export const MAX_PARSED_CONTENT_CHARS = 120_000
